---
- name: Installing htpd service on the server
  hosts: webserver
  become: yes
  tasks:
  - name:  check if file already exists
    stat:
     path: /home/nyadaur/copyscript.sh
    register: file
  - debug:
       var: file.stat.exists
  - name: backup the file if it already esists
    command: mv /home/nyadaur/copyscript.sh /home/nyadaur/bkp-copyscript.sh
    when: file.stat.exists
  - name: copy the script
    copy:
      src: /var/lib/jenkins/workspace/ansi-git-jenkins/copyscript.sh
      dest: /home/nyadaur
      mode: 0777
