---
- name: Installing htpd service on the server
  hosts: localhost
  become: yes
  tasks:
  - name: installing httpd
    yum:
       name: httpd
       state: present

  - name: Starting httpd service
    service:
       name: httpd
       state: started
  - name: Create a directoy
    file:
       path: /home/ec2-user/ansible-playbooks/test.txt
       state: touch

