---
- name: Installing htpd service on the server
  hosts: webserver
  become: yes
  tasks:
  - name:  check if file already exists
    stat:
     path: /home/nyadaur/test.txt
    register: file
  - debug:
       var: file.stat.exists
  - name: backup the file if it already esists
    command: mv /home/nyadaur/test.txt /home/nyadaur/bkp-test.txt
    when: file.stat.exists
  - name: copy the script
    copy:
      src: /var/lib/jenkins/workspace/ansi-git-jenkins/test.txt
      dest: /home/nyadaur
